// app/src/components/RegistrationForm/RegistrationForm.svelte
<script>
  import { navigate } from 'svelte-routing';
  import { onMount, onDestroy } from 'svelte';
  import {
    globalBtn1,
    globalErrorTxt,
    globalInput,
    globalLabel,
  } from '../../globals/global-styles.js';
  import { noneAreBlank } from '../../globals/validations.js';
  import {
    formHead,
    formBody,
    formWrap,
    loginHeader,
    smallText,
  } from '../LoginForm/LoginFormStyles.js';
  import { postRequest } from '../../globals/helpers.js';
  import { username } from '../../store/global-store.js';

  // props
  export let goToLogin;

  //state
  let loginName = '';
  let password = '';
  let confirmPassword = '';
  let email = '';
  let dirty = false;

  const handleEnterPress = e => e.keyCode === 13 && register();
  onMount(() => window.addEventListener('keypress', handleEnterPress));
  onDestroy(() => window.removeEventListener('keypress', handleEnterPress));

  async function register() {
    dirty = true;

    const registerPayload = {
      username: loginName,
      password,
      confirmPassword,
      email,
    };

    if (!noneAreBlank(loginName, password, confirmPassword, email)) {
      return;
    }

    const data = await postRequest('/authenticate/register', registerPayload);

    if (data && data.success) {
      username.set(loginName);
      navigate('/dashboard', { replace: true });
      return;
    }

    alert(
      'Registration failed. Did you already register with this username? Try a different username and try again.'
    );
  }
</script>

<div class={formWrap}>
  <div class={formHead}>
    <h3 class={loginHeader}>Registration Form</h3>
  </div>
  <div class={formBody}>
    <div class={globalLabel}>Username</div>
    <input bind:value={loginName} class={globalInput} />
    {#if dirty && !loginName}
      <div class={globalErrorTxt}>Username is required.</div>
    {/if}
    <div class={globalLabel}>Password</div>
    <input bind:value={password} class={globalInput} type="password" />
    {#if dirty && !password}
      <div class={globalErrorTxt}>Password is required.</div>
    {/if}
    <div class={globalLabel}>Confirm Password</div>
    <input bind:value={confirmPassword} class={globalInput} type="password" />
    {#if dirty && !confirmPassword}
      <div class={globalErrorTxt}>Confirm password is required.</div>
    {/if}
    <div class={globalLabel}>Email</div>
    <input bind:value={email} class={globalInput} />
    {#if dirty && !email}
      <div class={globalErrorTxt}>Email is required.</div>
    {/if}
    <button on:click={register} class={globalBtn1}>REGISTER</button>
    <div on:click={() => goToLogin(true)} class={smallText}>Already have an account?</div>
  </div>
</div>

// client/src/components/RegistrationForm/RegistrationForm.tsx
import React, { useState, useRef, useEffect, useContext } from 'react';
import { INewUser, IRegistrationForm } from '../../../../constants/interfaces';
import { postData } from '../../helpers/api';
import { displayRequiredErrMsg, checkVars } from '../../helpers/validations';
import GlobalContext from '../../contexts/global/GlobalContext';
import { ACTION_TYPES } from '../../contexts/global/GlobalActions';
import { history } from '../../App';

function RegistrationForm(props: IRegistrationForm): JSX.Element {
  const { goToLogin } = props;

  // Global Context State
  const { dispatch } = useContext(GlobalContext);

  // Local State
  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [confirmPassword, setConfirmPassword] = useState<string>('');
  const [email, setEmail] = useState<string>('');

  // Validations
  const requiredVariables: Array<any> = [
    username,
    password,
    confirmPassword,
    email,
  ];
  const [dirty, setDirty] = useState<boolean>(false);
  const [failedRegistration, setFailedRegistration] = useState<boolean>(false);
  const displayRequiredErr: (val: any) => boolean = displayRequiredErrMsg(
    dirty
  );

  useEffect(() => {
    window.addEventListener('keypress', handleEnterBtn);
    return () => window.removeEventListener('keypress', handleEnterBtn);
  }, []);

  const handleEnterBtn = (e: KeyboardEvent) => {
    if (e.keyCode === 13 && registerBtn && registerBtn.current) {
      registerBtn.current.click();
    }
  };

  // refs
  const registerBtn = useRef<HTMLButtonElement>(null);

  const register = async () => {
    setDirty(true);
    const registerPayload: INewUser = {
      username,
      password,
      confirmPassword,
      email,
    };

    if (checkVars(requiredVariables)) {
      const data = await postData(
        '/authenticate/register',
        JSON.stringify(registerPayload)
      );

      if (data.success) {
        dispatch({ type: ACTION_TYPES.UPDATE_LOGIN, payload: true });
        history.push('/dashboard');
      } else {
        setFailedRegistration(true);
      }
    }
  };

  return (
    <div className="RegistrationForm">
      <div className="RegistrationForm__head">
        <h3 className="RegistrationForm__heading">Registration</h3>
      </div>
      <div className="RegistrationForm__body">
        <div className="RegistrationForm__label">Username</div>
        <input
          onChange={e => setUsername(e.target.value)}
          className="RegistrationForm__input"
          type="text"
        />
        {displayRequiredErr(username) && (
          <div className="Global__error-msg">Username is required</div>
        )}
        <div className="RegistrationForm__label">Password</div>
        <input
          onChange={e => setPassword(e.target.value)}
          className="RegistrationForm__input"
          type="password"
        />
        {displayRequiredErr(password) && (
          <div className="Global__error-msg">Password is required</div>
        )}
        <div className="RegistrationForm__label">Confirm Password</div>
        <input
          onChange={e => setConfirmPassword(e.target.value)}
          className="RegistrationForm__input"
          type="password"
        />
        {displayRequiredErr(confirmPassword) && (
          <div className="Global__error-msg">Confirm Password is required</div>
        )}
        <div className="RegistrationForm__label">Email</div>
        <input
          onChange={e => setEmail(e.target.value)}
          className="RegistrationForm__input"
          type="text"
        />
        {displayRequiredErr(email) && (
          <div className="Global__error-msg">Email is required</div>
        )}
        {failedRegistration && (
          <div className="Global__error-msg">
            Registration Failed. Please try again.
          </div>
        )}
        <button
          onClick={register}
          className="RegistrationForm__btn"
          ref={registerBtn}
        >
          Register
        </button>
        <p
          className="RegistrationForm__already-have"
          onClick={() => goToLogin(true)}
        >
          Already have an account?
        </p>
      </div>
    </div>
  );
}

export default RegistrationForm;
