// client/src/components/LoginForm/LoginForm.tsx
import React, { useState, useContext, useEffect, useRef } from 'react';
import { ICredentials, ILoginForm } from '../../../../constants/interfaces';
import { postData } from '../../helpers/api';
import { displayErrMsg, checkVars } from '../../helpers/validations';
import { history } from '../../App';
import GlobalContext from '../../contexts/global/GlobalContext';
import { ACTION_TYPES } from '../../contexts/global/GlobalActions';

function LoginForm(props: ILoginForm): JSX.Element {
  const { goToRegister } = props;
  // global state
  const { dispatch } = useContext(GlobalContext);

  //local state
  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');

  // validations
  const [failedLogin, setFailedLogin] = useState<boolean>(false);
  const [dirty, setDirty] = useState<boolean>(false);
  const requiredVariables: Array<any> = [username, password];
  const displayErr: (val: any) => boolean = displayErrMsg(dirty);

  useEffect(() => {
    window.addEventListener('keypress', handleEnterBtn);
    return () => window.removeEventListener('keypress', handleEnterBtn);
  }, []);
  const loginBtn = useRef<HTMLButtonElement>(null);

  const handleEnterBtn = (e: KeyboardEvent) => {
    if (e.keyCode === 13 && loginBtn && loginBtn.current) {
      loginBtn.current.click();
    }
  };

  const login = async () => {
    setDirty(true);

    const loginPayload: ICredentials = {
      username,
      password,
    };

    if (checkVars(requiredVariables)) {
      const data = await postData(
        '/authenticate/login',
        JSON.stringify(loginPayload)
      );

      if (data.success) {
        dispatch({ type: ACTION_TYPES.UPDATE_LOGIN, payload: true });
        history.push('/dashboard');
      } else {
        setFailedLogin(true);
      }
    }
  };

  return (
    <div className="RegistrationForm">
      <div className="RegistrationForm__head">
        <h3 className="RegistrationForm__heading">Login</h3>
      </div>
      <div className="RegistrationForm__body">
        <div className="RegistrationForm__label">Username</div>
        <input
          className="RegistrationForm__input"
          onChange={e => setUsername(e.target.value)}
          type="text"
        />
        {displayErr(username) && (
          <div className="error-msg">Username is required.</div>
        )}
        <div className="RegistrationForm__label">Password</div>
        <input
          className="RegistrationForm__input"
          onChange={e => setPassword(e.target.value)}
          type="password"
        />
        {displayErr(password) && (
          <div className="error-msg">Password is required.</div>
        )}
        {failedLogin && (
          <div className="error-msg">Login Failed. Please try again.</div>
        )}
        <button
          className="RegistrationForm__btn"
          onClick={login}
          ref={loginBtn}
        >
          Login
        </button>
        <p
          className="RegistrationForm__already-have"
          onClick={() => goToRegister(false)}
        >
          Create New Account
        </p>
      </div>
    </div>
  );
}

export default LoginForm;

// app/src/components/LoginForm/LoginForm.svelte
<script>
  import { navigate } from 'svelte-routing';
  import { onMount, onDestroy } from 'svelte';
  import {
    globalBtn1,
    globalErrorTxt,
    globalInput,
    globalLabel,
  } from '../../globals/global-styles.js';
  import { noneAreBlank } from '../../globals/validations.js';
  import { formHead, formBody, formWrap, loginHeader, smallText } from './LoginFormStyles.js';
  import { username } from '../../store/global-store.js';
  import { postRequest } from '../../globals/helpers.js';

  // props
  export let goToRegistration;

  // state
  let loginName = '';
  let password = '';
  let failedLogin = false;
  let dirty = false;

  const handleEnterPress = e => e.keyCode === 13 && login();
  onMount(() => window.addEventListener('keypress', handleEnterPress));
  onDestroy(() => window.removeEventListener('keypress', handleEnterPress));

  async function login() {
    dirty = true;

    if (!noneAreBlank(loginName, password)) {
      return;
    }

    const data = await postRequest('/authenticate/login', { username: loginName, password });
    if (data && data.success) {
      username.set(loginName);
      navigate('/dashboard', { replace: true });
      return;
    }

    failedLogin = true;
  }
</script>

<div class={formWrap}>
  <div class={formHead}>
    <h3 class={loginHeader}>Login Form</h3>
  </div>
  <div class={formBody}>
    <div class={globalLabel}>Username</div>
    <input bind:value={loginName} class={globalInput} />
    {#if dirty && !loginName}
      <div class={globalErrorTxt}>Username is required.</div>
    {/if}
    <div class={globalLabel}>Password</div>
    <input bind:value={password} class={globalInput} type="password" />
    {#if dirty && !password}
      <div class={globalErrorTxt}>Password is required.</div>
    {/if}
    {#if failedLogin}
      <div class={globalErrorTxt}>Login Failed. Please try again.</div>
    {/if}
    <button class={globalBtn1} on:click={login}>LOGIN</button>
    <div class={smallText} on:click={() => goToRegistration(false)}>Create New Account</div>
  </div>
</div>
