// client/src/components/RandomQuote/RandomQuote.tsx
import React from 'react';
import { IRandomQuote } from '../../../../constants/interfaces';

const quotes: Array<IRandomQuote> = [
  {
    text: 'A despondent heart will always be defeated regardless of all skill.',
    author: 'Ringeck',
  },
];

function RandomQuote(): JSX.Element {
  const randomIndex: number = Math.floor(Math.random() * quotes.length);
  const { text, author }: IRandomQuote = quotes[randomIndex];
  return (
    <div className="RandomQuote">
      <p className="RandomQuote__text">“{text}"</p>
      <div className="RandomQuote__text">-{author}-</div>
    </div>
  );
}

export default RandomQuote;

// app/src/components/RandomQuote/RandomQuote.svelte
<script>
  import { quoteWrapper, quoteText } from './RandomQuoteStyles.js';
  const quotes = [
    {
      text: 'A despondent heart will always be defeated regardless of all skill.',
      author: 'Ringeck',
    },
  ];

  let { text, author } = quotes[Math.floor(Math.random() * quotes.length)];
</script>

<div class={quoteWrapper}>
  <p class={quoteText}>“{text}"</p>
  <div class={quoteText}>-{author}-</div>
</div>
