// client/src/pages/JudgesTable/JudgesTable.tsx
import React, { useState } from 'react';
import Competitor from '../../components/Competitor/Competitor';
import uuid from 'uuid/v1';
import { postData } from '../../helpers/api';
import { history } from '../../App';
import '../../scss/pages/judges-table.scss';

function JudgesTable(): JSX.Element {
  // Local State
  const [competitor1Score, setCompetitor1Score] = useState(0);
  const [competitor1Penalties, setCompetitor1Penalties] = useState(0);
  const [comp1Name, setComp1Name] = useState('');
  const [competitor2Score, setCompetitor2Score] = useState(0);
  const [competitor2Penalties, setCompetitor2Penalties] = useState(0);
  const [comp2Name, setComp2Name] = useState('');
  const [namesSubmitted, setNamesSubmitted] = useState(false);
  const [round, setRound] = useState(1);

  const handleScoreAdjust = (
    e: React.MouseEvent,
    num: number,
    comp: string
  ) => {
    switch (comp) {
      case 'comp1':
        if (competitor1Score + num >= 0) {
          setCompetitor1Score(competitor1Score + num);
        }
        break;
      case 'comp2':
        if (competitor2Score + num >= 0) {
          setCompetitor2Score(competitor2Score + num);
        }
      default:
        break;
    }
  };

  const handlePenaltyAdjust = (
    e: React.MouseEvent,
    num: number,
    comp: string
  ) => {
    switch (comp) {
      case 'comp1':
        if (
          competitor1Penalties + num >= 0 &&
          competitor1Penalties + num <= 5
        ) {
          setCompetitor1Penalties(competitor1Penalties + num);
        }
        break;
      case 'comp2':
        if (
          competitor2Penalties + num >= 0 &&
          competitor2Penalties + num <= 5
        ) {
          setCompetitor2Penalties(competitor2Penalties + num);
        }
      default:
        break;
    }
  };

  const handleNameChange = (e: React.FormEvent<HTMLInputElement>): void => {
    switch (e.currentTarget.name) {
      case 'comp1':
        setComp1Name(e.currentTarget.value);
        break;
      case 'comp2':
        setComp2Name(e.currentTarget.value);
        break;
      default:
        break;
    }
  };

  const handleSubmitNames = () => {
    if (comp1Name && comp2Name) {
      setNamesSubmitted(true);
    }
  };

  const toggleNamesSubmitted = () => {
    setNamesSubmitted(!namesSubmitted);
  };

  const handleSubmitScore = async () => {
    let winner =
      competitor1Score - competitor2Score > 0
        ? comp1Name
        : competitor1Score - competitor2Score < 0
        ? comp2Name
        : 'tie';

    let matchResults = {
      round,
      fighter1: comp1Name,
      fighter2: comp2Name,
      winner,
      event: 'Fight between 1 and 2.',
      tournamentId: uuid(),
    };
    const response = await postData(
      'score/save-match-result',
      JSON.stringify(matchResults)
    );

    if (response.success) {
      setRound(round + 1);
      setCompetitor1Score(0);
      setCompetitor2Score(0);
      alert(response.status);
    }
  };

  const handleRoundChange = (e: React.FormEvent<HTMLInputElement>): void => {
    if (parseInt(e.currentTarget.value) >= 0) {
      setRound(parseInt(e.currentTarget.value));
    }
  };

  return (
    <div>
      <h1 className="JudgesTable__title">Judge's Table</h1>
      <div>
        {!namesSubmitted ? (
          <div className="JudgesTable__name-input-container">
            <div className="JudgesTable__name-input-block">
              <label className="JudgesTable__label" htmlFor="comp1">
                Competitor 1
              </label>
              <input
                name="comp1"
                value={comp1Name}
                type="text"
                onChange={handleNameChange}
              />
            </div>
            <h3 className="JudgesTable__vs-text">VS</h3>
            <div className="JudgesTable__name-input-block">
              <label className="JudgesTable__label" htmlFor="comp2">
                Competitor 2
              </label>
              <input
                name="comp2"
                value={comp2Name}
                type="text"
                onChange={handleNameChange}
              />
            </div>
            <div className="JudgesTable__button-container">
              <button
                className="JudgesTable__button"
                onClick={handleSubmitNames}
              >
                Submit Names
              </button>
            </div>
          </div>
        ) : (
          <div className="JudgesTable__competitors-container">
            <Competitor
              competitor={comp1Name}
              competitorNum={'comp1'}
              competitorScore={competitor1Score}
              handleScoreAdjust={handleScoreAdjust}
              handlePenaltyAdjust={handlePenaltyAdjust}
              penaltyCount={competitor1Penalties}
            />

            <Competitor
              competitor={comp2Name}
              competitorNum={'comp2'}
              competitorScore={competitor2Score}
              handleScoreAdjust={handleScoreAdjust}
              handlePenaltyAdjust={handlePenaltyAdjust}
              penaltyCount={competitor2Penalties}
            />
            <div className="JudgesTable__buttons-container">
              <button
                className="JudgesTable__submit-button"
                onClick={handleSubmitScore}
              >
                Submit Final Score
              </button>
              <button
                className="JudgesTable__edit-names-button"
                onClick={toggleNamesSubmitted}
              >
                Edit Names
              </button>
              <div className="JudgesTable__round-container">
                <h3>Round</h3>
                <input
                  className="JudgesTable__round-input"
                  type="number"
                  onChange={handleRoundChange}
                  value={round}
                />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default JudgesTable;

// app/src/pages/JudgesTable/JudgesTable.svelte
<script>
  import {
    JudgesTableTitle,
    JudgesTableNameInputContainer,
    JudgesTableNameInputBlock,
    JudgesTableLabel,
    JudgsTableVSText,
    JudgesTableButtonContainer,
    JudgesTableButton,
    JudgesTableCompetitorsContainer,
    JudgesTableButtonsContainer,
    JudgesTableSubmitButton,
    JudgesTableEditNamesButton,
    JudgesTableRoundContainer,
    JudgesTableRoundInput,
  } from './JudgesTableStyles.js';
  import Competitor from '../../components/Competitor/Competitor.svelte';
  let namesSubmitted = false;
  let comp1Name;
  let competitor1Score = 0;
  let competitor1Penalties = 0;
  let comp2Name;
  let competitor2Score = 0;
  let competitor2Penalties = 0;
  let round = 1;

  function handleNameChange(e) {
    console.log('e.target.name: ', e.target.name);
    switch (e.target.name) {
      case 'comp1':
        comp1Name = e.target.value;
        break;
      case 'comp2':
        comp2Name = e.target.value;
        break;
      default:
        break;
    }
  }

  function handleSubmitNames() {
    console.log('handling submit names');
    namesSubmitted = comp1Name && comp2Name;
    // if (comp1Name && comp2Name) {
    //     namesSubmitted = true;
    // }
  }

  async function handleSubmitScore() {
    console.log('handleSubmitScore');
    let winner =
      competitor1Score - competitor2Score > 0
        ? comp1Name
        : competitor1Score - competitor2Score < 0
        ? comp2Name
        : 'tie';

    let matchResults = {
      round,
      fighter1: comp1Name,
      fighter2: comp2Name,
      winner,
      event: 'Fight between 1 and 2.',
      tournamentId: uuid(),
    };
    const response = await postData(
      'score/save-match-result',
      JSON.stringify(matchResults)
    );

    if (response.success) {
      round += 1;
      competitor1Score = 0;
      competitor2Score = 0;
      alert(response.status);
    }
  }

  function toggleNamesSubmitted() {
    console.log('toggleNamesSubmitted');
    namesSubmitted = !namesSubmitted;
  }

  function handleRoundChange() {
    if (parseInt(e.target.value) >= 0) {
      round = parseInt(e.target.value);
    }
  }

  function handleScoreAdjust(num, comp) {
    console.log('handleScoreAdjust: num', num);
    console.log('handleScoreAdjust comp: ', comp);
    switch (comp) {
      case 'comp1':
        if (competitor1Score + num >= 0) {
          competitor1Score = competitor1Score + num;
        }
        break;
      case 'comp2':
        if (competitor2Score + num >= 0) {
          competitor2Score = competitor2Score + num;
        }
      default:
        break;
    }
  }

  function handlePenaltyAdjust(num, comp) {
    switch (comp) {
      case 'comp1':
        if (
          competitor1Penalties + num >= 0 &&
          competitor1Penalties + num <= 5
        ) {
          competitor1Penalties = competitor1Penalties + num;
        }
        break;
      case 'comp2':
        if (
          competitor2Penalties + num >= 0 &&
          competitor2Penalties + num <= 5
        ) {
          setCompetitor2Penalties(competitor2Penalties + num);
        }
      default:
        break;
    }
  }
</script>

<style>

</style>

<div>
  <h1 class={JudgesTableTitle}>Judge's Table</h1>
  <div>
    {#if namesSubmitted}
      <div class={JudgesTableNameInputContainer}>
        <div class={JudgesTableNameInputBlock}>
          <label class={JudgesTableLabel} htmlFor="comp1">Competitor 1</label>
          <input
            name="comp1"
            value={comp1Name}
            type="text"
            on:change={handleNameChange} />
        </div>
        <h3 class={JudgsTableVSText}>VS</h3>
        <div class={JudgesTableNameInputBlock}>
          <label class={JudgesTableLabel} htmlFor="comp2">Competitor 2</label>
          <input
            name="comp2"
            value={comp2Name}
            type="text"
            on:change={handleNameChange} />
        </div>
        <div class={JudgesTableButtonContainer}>
          <button class={JudgesTableButton} onClick={handleSubmitNames}>
            Submit Names
          </button>
        </div>
      </div>
    {:else}
      <div class={JudgesTableCompetitorsContainer}>
        <Competitor
          competitor={comp1Name}
          competitorNum={'comp1'}
          competitorScore={competitor1Score}
          {handleScoreAdjust}
          {handlePenaltyAdjust}
          penaltyCount={competitor1Penalties} />

        <Competitor
          competitor={comp2Name}
          competitorNum={'comp2'}
          competitorScore={competitor2Score}
          {handleScoreAdjust}
          {handlePenaltyAdjust}
          penaltyCount={competitor2Penalties} />
        <div class={JudgesTableButtonsContainer}>
          <button class={JudgesTableSubmitButton} on:click={handleSubmitScore}>
            Submit Final Score
          </button>
          <button
            class={JudgesTableEditNamesButton}
            on:click={toggleNamesSubmitted}>
            Edit Names
          </button>
          <div class={JudgesTableRoundContainer}>
            <h3>Round</h3>
            <input
              class={JudgesTableRoundInput}
              type="number"
              on:change={handleRoundChange}
              value={round} />
          </div>
        </div>
      </div>
    {/if}
  </div>
</div>
