// client/src/components/Header/Header.tsx
import React from 'react';
import { Link } from 'react-router-dom';
// @ts-ignore
import Logo from '../../../assets/images/logo.png';

function Header(): JSX.Element {
  return (
    <div className="Header">
      <Link to="/">
        <img
          className="Header__logo"
          src={Logo}
          alt="Sword Point HEMA Tournament Software"
        />
      </Link>
      <div className="Header__links-wrap">
        <Link to="/">Home</Link>
        <Link to="/">Home</Link>
        <Link to="/">Home</Link>
        <Link to="/">Home</Link>
      </div>
    </div>
  );
}

export default Header;

// HemaSite/Client/src/components/Header/Header.svelte
<script>
  import { headerWrap, logoImg, linksWrap } from './HeaderStyles.js';
  import { Link } from 'svelte-routing';
  import { username } from '../../store/global-store.js';
  import { validatedRoute } from '../../globals/helpers.js';
</script>

<div class={headerWrap}>
  <Link to={validatedRoute($username, '/')}>
    <img
      class={logoImg}
      src="/images/sword-point-white.svg"
      alt="Sword Point HEMA Tournament Software" />
  </Link>
  <ul class={linksWrap}>
    <li>HOME</li>
    <li>HOME</li>
    <li>HOME</li>
    <li>HOME</li>
  </ul>
</div>
