// client/src/components/UpcomingTournamentCard/UpcomingTournamentCard.tsx
import React, { FC } from 'react';
import { INewTournament } from '../../../../constants/interfaces';
import { formatDate } from '../../helpers/helpers';

const UpcomingTournamentCard: FC<INewTournament> = ({
  tournamentName,
  hostClub,
  startDate,
  endDate,
  uuid,
}): JSX.Element => {
  const goToTournamentView = () => {
    window.location.href = `/view-tournament?tournamentId=${uuid}`;
  };

  return (
    <div onClick={goToTournamentView} className="UpcomingTournamentCard">
      <h3>{tournamentName}</h3>
      <div>
        <div>Hosted by: {hostClub}</div>
        <div>Dates: {`${formatDate(startDate)} - ${formatDate(endDate)}`}</div>
      </div>
    </div>
  );
};

export default UpcomingTournamentCard;

// HemaSite/Client/src/components/UpcomingTournamentCard/UpcomingTournamentCard.svelte
<script>
  import { card } from './UpcomingTournamentCardStyles';
  import { formatDate } from '../../globals/helpers.js';
  export let tournamentName = '';
  export let hostClub = '';
  export let startDate = '';
  export let endDate = '';
  export let uuid;

  const goToTournamentView = () => {
    window.location.href = `/view-tournament?tournamentId=${uuid}`;
  };
</script>

<div on:click={goToTournamentView} class={card}>
  <h3>{tournamentName}</h3>
  <div>
    <div>Hosted by: {hostClub}</div>
    <div>Dates: {`${formatDate(startDate)} - ${formatDate(endDate)}`}</div>
  </div>
</div>
